name: Sleep Number
description: Recorded the time
inputs:
  order-number:
    description: Order Number
    required: true
    default: "0000"
  ordered-date:
    description: Ordered Date
    required: true
    default: "0000"
outputs:
  time:
    description: The time we greeted you
build:
  using: docker
  image: Dockerfile
  args:
    - orderNumber = ${{ inputs.order-number }}
    - date = ${{ inputs.ordered-date }}
runs:
  using: docker
  image: Dockerfile
  args:
    - orderNumber = ${{ inputs.order-number }}
    - date = ${{ inputs.ordered-date }}
