name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  order-number:  # id of input
    description: 'Order Number'
    required: true
    default: '0000'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'orderNumber = ${{ inputs.order-number }}'
