name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      who-to-greet: null
      description: whom to greet
      required: true
      default: world
    outputs:
      time:
        description: The time we greeted you
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        runs: 'echo Hello, world!'
