name: Manual workflow
'on':
  workflow_dispatch:
    inputs:
      First_Name:
        description: Person First Name
        required: true
        default: Java
      Last name: null
    output:
      time:
        description: The time we greeted you
    runs: null
    using: docker
    image: Dockerfile
    args:
      - 'sadasd'
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: >-
          echo "Hello ${{ github.event.inputs.FirstName }} ${{
          github.event.inputs.LastName }}"
