name: Manual workflow
'on':
  workflow_dispatch:
    inputs:
      order-number:
        description: Order Number
        required: true
        default: 000000
  
    
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SQL/Order Status
    steps:
      - name: Sleep Number Job
        id: Deploy
        uses: actions/SpringBootTest
        with:
          order-number: orderNumber = ${{inputs.order-number}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.Deploy.outputs.time }}"
