name: Manual workflow
'on':
  workflow_dispatch:
    inputs:
      order-number:
        description: Order Number
        required: true
        default: 000000
      ordered-date:
        description: Ordered Date
        required: true
        default: "01-JAN-000"

    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SQL/Order Status
    steps:
      - name: Sleep Number Job
        id: Deploy
        uses:  arun1950march/SpringBootTest@main
        with:
          dockerfile: ./app/Dockerfile
          context: app
          push: false
          tags: myimage:latest
          order-number: ${{inputs.order-number}}
          ordered-date: ${{inputs.ordered-date}}
         
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          mkdir -p path/to/artifact-A
          mkdir -p path/to/artifact-B
          echo "Lorem ipsum dolor sit amet" > path/to/artifact-A/file-A.txt
