name: Manual workflow
'on':
  workflow_dispatch:
    inputs:
      order-number:
        description: Order Number
        required: true
        default: 000000
      ordered-date:
        description: Ordered Date
        required: true
        default: "01-JAN-000"
    
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SQL/Order Status
    steps:
      - name: Sleep Number Job
        id: Deploy
        uses: arun1950march/SpringBootTest@main
        with:
          order-number: ${{inputs.order-number}}
          ordered-date: ${{inputs.ordered-date}}
          build-args: |
           - ordered-date=${{ inputs.ordered-date }} 
           - order-number=${{ inputs.order-number }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.Deploy.outputs.time }}"
